# Said Moussadeqimport random# -------------------------------------------------------------------# this is the generateNumber function# it has one parameter:#   'topLimit' which is the top limit for the random number generator# the function returns the random number generated to its callerdef generateNumber( topLimit ):
    secretNumber = random.randint(1,topLimit)
    return secretNumber



# end of generateNumber function -------------------------------------
# -------------------------------------------------------------------# this is the askUserToGuess function# it has two parameters:#   the 'times' parameter is the number of guesses allowed#   the 'secretNumber' parameter is the secret, random number# the function returns one of two values:#   return True if the user guessed the answer correctly#   return False if the user did not guess the answer correctlydef askUserToGuess( times, secretNumber ):    # this loop cycles through all the user guesses    for guessesTaken in range(1, times+1):        print('Take your guess #' + str(guessesTaken) + ': ')        guess = int(input())        if evaluateAnswer( guess, secretNumber ) == True:            return True            return False# end of askUserToGuess function ----------------------------------# -------------------------------------------------------------------# this is the evaluateAnswer function# it has two parameters:#   the 'userGuess' parameter is the answer entered by the user#   the 'userSecretNumber' parameter is the randomly generated numberdef evaluateAnswer( userGuess, userSecretNumber ):    if userGuess < userSecretNumber:	print('Your guess is too low')	return False    elif userGuess > userSecretNumber:	print('Your guess is too high')	return False    else: userGuess == userScretNumber    return True
# end of evaluateAnswer function -------------------------------------# -------------------------------------------------------------------# this is the playGame function# it has one parameter:#   'showAnswer' is a Boolean value, if that Boolean value is:#       True, we'll show the right answer on the screen#       False, we won't show the right answer on the screendef playGame(showAnswer):
    print('welcome to guess the number game')
    print('Think of a number between 1 to a number of your choice')
    orange = int(input())
    print('how many guesses would you like to take?')    totalGuesses = int(input())    theNumber = generateNumber(orange)    print( 'The remaining guess you have is ' + str(totalGuesses)+ ' to guess between 1 and ' + str(orange))

    # you don't need to change anything below this comment ##############    # ///////////////////////////////////////////////////////////////////    # this if statement allows us to show the hidden number to the user    if( showAnswer == True ):        print('--shhh, the real number is ' + str(theNumber) + '.')        #this gives a sucess/fail message if the user guessed correctly in the allotted attempts    if askUserToGuess(totalGuesses,theNumber) == True:        print('Good job! You guessed my number!')    else:        print('Nope. The number I was thinking of was ' + str(theNumber))# end of playGame function -----------------------------------------